enableSodiumMenu = true
useBlockStateCulling = true
useCustomItemFrameRenderer = true
useItemFrameLOD = true
itemFrameLODRange = 80
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 12.0
leavesCullingMode = "DEPTH"
leavesCullingDepth = 2
powderSnowCulling = true
